const group1 = require("../../../../assets/img/stream.png");
const group2 = require("../../../../assets/img/planos.png");
const group3 = require("../../../../assets/img/adobe.png");
const group4 = require("../../../../assets/img/antivirus.png");
const group5 = require("../../../../assets/img/software.png");
const group6 = require("../../../../assets/img/VPN.png");

export const Touchables = [
  {
    title: "Todos",
    key: 0,
  },

  {
    title: "Depoimento",
    key: 1,
  },
  {
    title: "Narração",
    key: 2,
  },
  {
    title: "Edição de foto",
    key: 3,
  },
  {
    title: "Videos",
    key: 4,
  },
  {
    title: "Arte para post",
    key: 5,
  },
];
export const Group = [
  {
    source: Group,
    key1: "groupkey1",
    key2: "groupkey2",
    key3: "groupkey3",
    key4: "groupkey4",
    key5: "groupkey5",
    key6: "groupkey6",
    key7: "groupkey7",
    key8: "groupkey8",
    key9: "groupkey9",
    key10: "groupkey10",
    key11: "groupkey11",
    key12: "groupkey12",
    name: "Netflix",
    price: "15,99",
    places: 1,
    priceDescription: "15,99",
    placesDescription: "Vagas:",
  },
  {
    source: group2,
    key1: "group2key1",
    key2: "group2key2",
    key3: "group2key3",
    key4: "group2key4",
    key5: "group2key5",
    key6: "group2key6",
    key7: "group2key7",
    key8: "group2key8",
    key9: "group2key9",
    key10: "group2key10",
    key11: "group2key11",
    key12: "group2key12",
    name: "Xbox",
    price: "15,99",
    places: 1,
    priceDescription: "15,99",
    placesDescription: "Vagas:",
  },
  {
    source: group3,
    key1: "group3key1",
    key2: "group3key2",
    key3: "group3key3",
    key4: "group3key4",
    key5: "group3key5",
    key6: "group3key6",
    key7: "group3key7",
    key8: "group3key8",
    key9: "group3key9",
    key10: "group3key10",
    key11: "group3key11",
    key12: "group3key12",
    name: "Photoshop",
    price: "15,99",
    places: 1,
    priceDescription: "15,99",
    placesDescription: "Vagas:",
  },
  {
    source: group4,
    key1: "group4key1",
    key2: "group4key2",
    key3: "group4key3",
    key4: "group4key4",
    key5: "group4key5",
    key6: "group4key6",
    key7: "group4key7",
    key8: "group4key8",
    key9: "group4key9",
    key10: "group4key10",
    key11: "group4key11",
    key12: "group4key12",
    name: "Karspersky",
    price: "15,99",
    places: 1,
    priceDescription: "15,99",
    placesDescription: "Vagas:",
  },
  {
    source: group5,
    key1: "group5key1",
    key2: "group5key2",
    key3: "group5key3",
    key4: "group5key4",
    key5: "group5key5",
    key6: "group5key6",
    key7: "group5key7",
    key8: "group5key8",
    key9: "group5key9",
    key10: "group5key10",
    key11: "group5key11",
    key12: "group5key12",
    name: "Office ",
    price: "15,99",
    places: 1,
    priceDescription: "15,99",
    placesDescription: "Vagas:",
  },
  {
    source: group6,
    key1: "group6key1",
    key2: "group6key2",
    key3: "group6key3",
    key4: "group6key4",
    key5: "group6key5",
    key6: "group6key6",
    key7: "group6key7",
    key8: "group6key8",
    key9: "group6key9",
    key10: "group6key10",
    key11: "group6key11",
    key12: "group6key12",
    name: "Nord vpn",
    price: "15,99",
    places: 1,
    priceDescription: "15,99",
    placesDescription: "Vagas:",
  },
];
