export const Inputs = [
  {
    key: "1",
    name: "Nome",
    marginY: 1,
    label: "Nome completo",
    placeholder: "Nome completo",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "2",
    name: "Telefone",
    marginY: 1,
    label: "Telefone",
    placeholder: "Telefone",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,
    secury: false,
    keyboardType: "numeric",
  },
  {
    key: "3",
    name: "Email",
    marginY: 1,
    label: "Email",
    placeholder: "Email",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,
    secury: false,
    keyboardType: "email-address",
    isDisabled: true,
  },
  {
    key: "4",
    name: "Senha",
    marginY: 1,
    placeholder: "********",
    label: "Senha",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,
    secury: true,
  },
  {
    key: "5",
    name: "Rsenha",
    placeholder: "********",
    label: "Repita a senha",
    width: "77.77%",
    height: 42,
    returnKeyType: "go",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,

    secury: true,
  },
];
